playUntil:
  - ROUND_COUNT
  #- STOP_LOSS
  #- STOP_GAIN
  #- BANKRUPT
roundCount: 2500000
stopLoss: 0.5   # down percentage
stopGain: 0.5
  
craps:
  field12PaysTriple: false
  tableMin: 10
  tableMax: 5000
  players:
    - bankroll: 1000
      bettingStrategy:
        - bet: craps.bets.PassLineBet
          amountStrategy: common.amountstrategy.TableMin
        - bet: craps.bets.PassLineOdds
          amountStrategy: craps.amountstrategy.ThreeFourFiveOdds

# see example at https://stackoverflow.com/questions/533048/how-to-log-source-file-name-and-line-number-in-python
logging:
  version: 1
  formatters:
    standard:
      format: '%(asctime)s [%(levelname)s] %(filename)s:%(lineno)d - %(message)s'
  handlers:
    default:
      level: 'DEBUG'
      formatter: 'standard'
      class: 'logging.StreamHandler'
      stream: 'ext://sys.stdout'
  loggers:
    '':
      handlers: ['default']
      level: 'INFO'
      propagate: true
