playUntil:
  - ROUND_COUNT
  #- STOP_LOSS
  #- STOP_GAIN
  #- BANKRUPT
rounds: 5 #2500000
stopLoss: 0.5   # down percentage
stopGain: 0.5
  
craps:
  field12PaysTriple: true
  tableMin: 10
  tableMax: 5000
  players:
    - bankroll: 1000
      bettingStrategy:
        - bet: craps.bets.PassLineBet
          amountStrategy: common.amount_strategy.TableMin
        - bet: craps.bets.PassLineOdds
          amountStrategy: craps.amountstrategy.ThreeFourFiveOdds.ThreeFourFiveOdds
        - bet: craps.bets.Come
          amountStrategy: common.amount_strategy.TableMin
        #- bet: craps.bets.FieldBet
        #  amountStrategy: common.amount_strategy.TableMin

# see example at https://stackoverflow.com/questions/533048/how-to-log-source-file-name-and-line-number-in-python
logging:
  version: 1
  formatters:
    standard:
      format: '%(asctime)s [%(levelname)s] %(filename)s:%(lineno)d - %(message)s'
  handlers:
    console:
      level: 'DEBUG'
      formatter: 'standard'
      class: 'logging.StreamHandler'
      stream: 'ext://sys.stdout'
    file:
      level: 'DEBUG'
      formatter: 'standard'
      class: 'logging.FileHandler'
      filename: './logs/pycasino.log'
  loggers:
    '':
      handlers: ['console', 'file']
      level: 'INFO'
      propagate: true
